### ISSUE TITLE
Hide show all subjects button in /grade6 page

### ISSUE THREAD

**Issue by coolbrg** [coolbrg/nossecondary#1]
<img width="308" alt="Screenshot 2020-07-24 at 10 10 07 PM" src="https://user-images.githubusercontent.com/1132451/88414485-8ed40880-cdfa-11ea-8d61-80c7fb929519.png">

We should not show `Show All Subjects` button in `/grade6` page as all the subjects are listed there already.

It makes sense to show the button during `/grade6/<subject>` url

**Comment by pyderator** [comment]
Show All subject is now not visible anymore in /grade6 route and is visible in /grade6/<subject>
